channelAdder/urls.py
from django.conf.urls import url
from .views import *
#url for app

app_name = 'channelAdder'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-channel/', add_channel, name='add-channel'),
]

home/urls.py
from django.conf.urls import url
from .views import *
#url for app

app_name = 'home'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-message/', add_message, name='add-message'),
    url(r'^add-message-api/', add_message_api, name="add_message_api"),
]

messageBroadcaster/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include,url
from django.contrib import admin
from django.urls import path
import home.urls as home
import channelAdder.urls as channelAdder

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^home/', include(home,namespace='home')),
    url(r'^channelAdder/', include(channelAdder,namespace='channelAdder')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

channelAdder/models.py
from django.db import models

# Create your models here.
class Routers(models.Model):
    routingKey = models.CharField(max_length=255,blank=True,unique=True)
    count = models.IntegerField()

home/models.py
from django.db import models
from channelAdder.models import Routers
# Create your models here
class Messages(models.Model):
    routingKey = models.ForeignKey(Routers, default=None, on_delete=models.CASCADE,related_name="router")
    dateTime = models.DateTimeField()
    message = models.CharField(max_length=100000,blank=True)
    messageType = models.CharField(max_length=255, blank=True)
    image = models.FileField(upload_to='images/', default="noImage")

    @property	
    def photo_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

channelAdder/forms.py
from django import forms

class Record_Form(forms.Form):
    message = forms.CharField(widget=forms.TextInput(attrs={'type': 'text',
        'class' : 'form-control'}), label="Notification Channel Name")

home/forms.py
from django import forms
from .models import Routers

class Record_Form(forms.Form):
    message = forms.CharField(widget=forms.Textarea(attrs={'type': 'text',
		'cols' : 90,
		'rows' : 10,
        'class' : 'form-control'}), label="Message")
    date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control' }))
    notification_channel = forms.ModelChoiceField(queryset=Routers.objects.values_list("routingKey",flat=True).distinct(),empty_label=None,label="Notification Channel:",widget=forms.Select(attrs={'class':'form-control'}),required=True)
    priority = forms.ChoiceField(choices=[('Important','Important'),('General','General'),('Targeted','Targeted'),('All Devices','All Devices')],label="Message Type",widget=forms.Select(attrs={'class':'form-control'}),required=True)
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class':'form-control-file'}),label="Notification Image",required=False)

channelAdder/views.py
from django.shortcuts import render
from .forms import Record_Form
from .models import Routers
from django.http import HttpResponseRedirect

# Create your views here.
response = {}


def index(request):
    response['forms'] = Record_Form
    response['routers'] = Routers.objects.all()
    return render(request, 'index1.html', response)


def add_channel(request):
    form = Record_Form(request.POST or None)
    if (request.method == 'POST'):
        response['notifChannelName'] = request.POST['message']
        todo = Routers(routingKey=response['notifChannelName'], count=0)
        todo.save()
        return HttpResponseRedirect('/home/')
    else:
        return HttpResponseRedirect('/home/')

home/views.py
from django.shortcuts import render
from .tasks import publisher
from .forms import Record_Form
import datetime
from .models import Messages
from channelAdder.models import Routers
from django.http import HttpResponseRedirect
from django.utils import timezone
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

# Create your views here.
response = {}


def index(request):
    response['forms'] = Record_Form
    return render(request, 'index.html', response)


def add_message(request):
    form = Record_Form(request.POST or None)
    if (request.method == 'POST'):
        messageId = -999
        response['message'] = request.POST['message']
        response['routingKey'] = request.POST['notification_channel']
        response['routing_channel'] = request.POST['priority']
        response['datetime'] = datetime.datetime.strptime(
            request.POST['date'], '%Y-%m-%dT%H:%M')
        imageProcess = request.FILES['image'] if 'image' in request.FILES else False
        if (imageProcess == False):
            response['image'] = 'noImage'
        else:
            response['image'] = request.FILES.get('image')
        current_tz = timezone.get_current_timezone()
        t2 = current_tz.localize(response['datetime'])
        todo = Messages(routingKey=Routers.objects.get(
            routingKey=response['routingKey']), message=response['message'], dateTime=t2, image=response['image'], messageType=response['routing_channel'])
        todo.save()
        messageId = todo.image.url
        print(messageId)
        Routers.objects.filter(routingKey=response['routingKey']).update(
            count=Routers.objects.get(routingKey=response['routingKey']).count + 1)
        
        publisher.apply_async(args=[response['routingKey']+"."+response['routing_channel'],
                                    response['message'], messageId, response['routing_channel']], eta=t2)
        return HttpResponseRedirect('/home/')
    else:
        return HttpResponseRedirect('/home/')


@api_view(['POST'])
def add_message_api(request):
    if request.method == 'POST':
        messageId = -999
        response['message'] = request.POST['message']
        response['datetime'] = request.POST['dateTime']
        response['routingKey'] = request.POST['channel']
        response['messageType'] = request.POST['messageType']
        response['datetime'] = datetime.datetime.strptime(
            request.POST['dateTime'], '%Y-%m-%dT%H:%M')
        imageProcess = request.FILES['imageUri'] if 'imageUri' in request.FILES else False
        if (imageProcess == False):
            response['image'] = 'noImage'
        else:
            response['image'] = request.FILES['imageUri']
        current_tz = timezone.get_current_timezone()
        t2 = current_tz.localize(response['datetime'])
        todo = Messages(routingKey=Routers.objects.get(
            routingKey=response['routingKey']), message=response['message'], dateTime=t2, image=response['image'],messageType=response['messageType'])
        todo.save()
        messageId = todo.image.url
        Routers.objects.filter(routingKey=response['routingKey']).update(
            count=Routers.objects.get(routingKey=response['routingKey']).count + 1)
        publisher.apply_async(
            args=[response['routingKey']+"."+response['messageType'], response['message'], messageId, response['messageType']], eta=t2)
        return Response(status=status.HTTP_201_CREATED)

channelAdder/templates/index1.html
{% load staticfiles %} {% load static %}


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>CheckYuk Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="Message Broadcaster">
    <meta name="msapplication-tap-highlight" content="no">
    <link href="{% static 'main.css' %}" rel="stylesheet">
</head>

<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                    </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6">
                                
                            </i>
                        </span>
                </button>
                </span>
            </div>
            <div class="app-header__content">
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        <img width="42" class="rounded-circle" src="{% static 'assets/images/account-circle-512.png' %}" alt="">
                                        <div class="widget-content-left  ml-3 header-user-info">
                                            <div class="widget-heading">
                                                {{ user.username }}
                                            </div>
                                            <div class="widget-subheading">
                                                Admin
                                            </div>
                                        </div>
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        <form action="/dashboard/user_logout" enctype="multipart/form-data">
                                            <button type="submit" class="btn-shadow p-1 btn btn-primary btn-sm">
                                            LOGOUT
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="app-main">
            <div class="app-sidebar sidebar-shadow">
                <div class="app-header__logo">
                    <div class="logo-src"></div>
                    <div class="header__pane ml-auto">
                        <div>
                            <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                                    <span class="hamburger-box">
                                        <span class="hamburger-inner"></span>
                                    </span>
                                </button>
                        </div>
                    </div>
                </div>
                <div class="app-header__mobile-menu">
                    <div>
                        <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                    </div>
                </div>
                <div class="app-header__menu">
                    <span>
                            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                                <span class="btn-icon-wrapper">
                                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                                </span>
                    </button>
                    </span>
                </div>
                <div class="scrollbar-sidebar">
                    <div class="app-sidebar__inner">
                        <ul class="vertical-nav-menu">
                            <li class="app-sidebar__heading">Dashboard</li>
                            <li>
                                <a href="/home/">
                                    <i class="metismenu-icon pe-7s-rocket"></i> Home
                                </a>
                            </li>
                            <li>
                                <a href="/channelAdder/" class="mm-active">
                                    <i class="metismenu-icon pe-7s-diamond"></i> Add Notification Channel
                                </a>
                            </li>
                            <!-- <li>
                                <a href="/verification/">
                                    <i class="metismenu-icon pe-7s-car"></i> Verify Item
                                </a>
                            </li> -->
                        </ul>
                    </div>
                </div>
            </div>
            <div class="app-main__outer">
                <div class="app-main__inner">
                    <div class="app-page-title">
                        <div class="page-title-wrapper">
                            <div class="page-title-heading">
                                <div class="page-title-icon">
                                    <i class="pe-7s-car icon-gradient bg-mean-fruit">
                                        </i>
                                </div>
                                <div>Welcome to Message Sender Dashboard
                                    <div class="page-title-subheading">This is where you try to send notifications
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="mb-3 card">
                                <div class="card-header-tab card-header-tab-animation card-header">
                                    <div class="card-header-title">
                                        <i class="header-icon lnr-apartment icon-gradient bg-love-kiss"> </i> Input Item
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="tab-content">
                                        <form id="form" method="post" action="{% url 'channelAdder:add-channel' %}" enctype="multipart/form-data" style="padding: 20px;">
                                            {% csrf_token %} {{ forms.as_p }}
                                            <input type="submit" id="submit" class="btn btn-primary" value="Submit">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="mb-3 card">
                                <div class="card-header-tab card-header-tab-animation card-header">
                                    <div class="card-header-title">
                                        <i class="header-icon lnr-apartment icon-gradient bg-love-kiss"> </i> Item list
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="tab-content">
                                        <table class="mb-0 table table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Notification Channel Name</th>
                                                    <th>Message Count</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% if routers %} {% for data in routers %}
                                                <tr>
                                                    <th scope="row">{{ data.routingKey }}</th>
                                                    <td>{{ data.count }}</td>
                                                </tr>
                                                {% endfor %}{% endif %}
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="app-wrapper-footer">
                        <div class="app-footer">
                            <div class="app-footer__inner">
                                <div class="app-footer-left">
                                    <ul class="nav">
                                        <li class="nav-item">
                                            All rights reserved. MessageBroadcaster 2020
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="{% static 'assets/scripts/main.js' %}"></script>
</body>

</html>

home/templates/index.html
{% load staticfiles %} {% load static %}


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>CheckYuk Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="Message Broadcaster">
    <meta name="msapplication-tap-highlight" content="no">
    <link href="{% static 'main.css' %}" rel="stylesheet">
</head>

<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                    </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6">
                                
                            </i>
                        </span>
                </button>
                </span>
            </div>
            <div class="app-header__content">
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        <img width="42" class="rounded-circle" src="{% static 'assets/images/account-circle-512.png' %}" alt="">
                                        <div class="widget-content-left  ml-3 header-user-info">
                                            <div class="widget-heading">
                                                {{ user.username }}
                                            </div>
                                            <div class="widget-subheading">
                                                Admin
                                            </div>
                                        </div>
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        <form action="/dashboard/user_logout" enctype="multipart/form-data">
                                            <button type="submit" class="btn-shadow p-1 btn btn-primary btn-sm">
                                            LOGOUT
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="app-main">
            <div class="app-sidebar sidebar-shadow">
                <div class="app-header__logo">
                    <div class="logo-src"></div>
                    <div class="header__pane ml-auto">
                        <div>
                            <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                                    <span class="hamburger-box">
                                        <span class="hamburger-inner"></span>
                                    </span>
                                </button>
                        </div>
                    </div>
                </div>
                <div class="app-header__mobile-menu">
                    <div>
                        <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                    </div>
                </div>
                <div class="app-header__menu">
                    <span>
                            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                                <span class="btn-icon-wrapper">
                                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                                </span>
                    </button>
                    </span>
                </div>
                <div class="scrollbar-sidebar">
                    <div class="app-sidebar__inner">
                        <ul class="vertical-nav-menu">
                            <li class="app-sidebar__heading">Dashboard</li>
                            <li>
                                <a href="/home/" class="mm-active">
                                    <i class="metismenu-icon pe-7s-rocket"></i> Home
                                </a>
                            </li>
                            <li>
                                <a href="/channelAdder/">
                                    <i class="metismenu-icon pe-7s-diamond"></i> Add Notification Channel
                                </a>
                            </li>
                            <!-- <li>
                                <a href="/verification/">
                                    <i class="metismenu-icon pe-7s-car"></i> Verify Item
                                </a>
                            </li> -->
                        </ul>
                    </div>
                </div>
            </div>
            <div class="app-main__outer">
                <div class="app-main__inner">
                    <div class="app-page-title">
                        <div class="page-title-wrapper">
                            <div class="page-title-heading">
                                <div class="page-title-icon">
                                    <i class="pe-7s-car icon-gradient bg-mean-fruit">
                                        </i>
                                </div>
                                <div>Welcome to Message Sender Dashboard
                                    <div class="page-title-subheading">This is where you try to send notifications
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="mb-3 card">
                                <div class="card-header-tab card-header-tab-animation card-header">
                                    <div class="card-header-title">
                                        <i class="header-icon lnr-apartment icon-gradient bg-love-kiss"> </i> Input Item
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="tab-content">
                                        <form id="form" method="post" action="{% url 'home:add-message' %}" enctype="multipart/form-data" style="padding: 20px;">
                                            {% csrf_token %} {{ forms.as_p }}
                                            <input type="submit" id="submit" class="btn btn-primary" value="Submit">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="app-wrapper-footer">
                        <div class="app-footer">
                            <div class="app-footer__inner">
                                <div class="app-footer-left">
                                    <ul class="nav">
                                        <li class="nav-item">
                                            All rights reserved. MessageBroadcaster 2020
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="{% static 'assets/scripts/main.js' %}"></script>
</body>

</html>